repository:
  name: "forge-python3"
  description: ""
  homepage: ""
  default_branch: master
  private: true
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true